/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Screen.java
 *
 * Created on 27.12.2012, 10:47:38
 */
package binpacking;
import java.util.*;
//import javax.swing.*;
/**
 *
 * @author Naty
 */
public class Screen extends javax.swing.JFrame {

    private BinPacking bp;
    /** Creates new form Screen */
    public Screen(BinPacking bp) {
        this.bp = bp;
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                initComponents();
                setVisible(true);
            }
        });
    }
    public void enableRepeatButton(){
   runExperimentButton.setEnabled(true);
}
    public void changeButtonsEnabled(){
        runButton.setEnabled(true);
        generateButton.setEnabled(true);
        stopButton.setEnabled(false);
    }
    public void setCyclesLabel(String s){
        cyclesLabel.setText(s);
    }
    public ResultPanel getResPanel() {
        return textPane;
    }
    public ResultPanel getGPanel(){
        return graphicPane;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        mainTab = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        objNum = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        maxSize = new javax.swing.JTextField();
        contNum = new javax.swing.JTextField();
        capacity = new javax.swing.JTextField();
        freeCap = new javax.swing.JTextField();
        generateButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        runButton = new javax.swing.JButton();
        stopButton = new javax.swing.JButton();
        resultTab = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane(textPane);
        textPane = new binpacking.ResultPanel(bp,false);
        jScrollPane2 = new javax.swing.JScrollPane(graphicPane);
        graphicPane = new binpacking.ResultPanel(bp,true);
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        experimentProgress = new javax.swing.JProgressBar(0,10);
        jLabel7 = new javax.swing.JLabel();
        stopTaskButton = new javax.swing.JButton();
        stopExperimentButton = new javax.swing.JButton();
        runExperimentButton = new javax.swing.JButton();
        cyclesLabel = new javax.swing.JLabel();
        taskProgressLabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        gObjects = new javax.swing.JTextField();
        gMaxSize = new javax.swing.JTextField();
        gFreeCapacity = new javax.swing.JTextField();
        gContainers = new javax.swing.JTextField();
        gCapacity = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel16 = new javax.swing.JLabel();
        gCycles = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        resultTable = new javax.swing.JTable();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bin Packing");

        mainTab.setPreferredSize(new java.awt.Dimension(500, 450));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Task Parameters");

        jLabel2.setText("Objects");

        objNum.setText(Integer.toString(bp.getVolumes().length));
        objNum.setText("10");
        /*
        objNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                objNumActionPerformed(evt);
            }
        });
        */

        jLabel3.setText("Max Size");

        jLabel4.setText("Containers");

        jLabel5.setText("Capacity");

        jLabel6.setText("Free Capacity");

        maxSize.setText("50");
        /*
        maxSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxSizeActionPerformed(evt);
            }
        });
        */

        contNum.setText("5");
        /*
        contNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contNumActionPerformed(evt);
            }
        });
        */

        capacity.setText("100");
        /*
        capacity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capacityActionPerformed(evt);
            }
        });
        */

        freeCap.setText("any");

        generateButton.setText("Generate");
        generateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(generateButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(13, 13, 13)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(contNum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(freeCap)
                                        .addComponent(capacity)
                                        .addComponent(objNum, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                                    .addComponent(maxSize, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))))
                        .addGap(19, 19, 19)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(objNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(maxSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(contNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(capacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(freeCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(generateButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setText("Algorithm");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Simple","Sub"}));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        runButton.setText("Run");
        runButton.setEnabled(false);
        runButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runButtonActionPerformed(evt);
            }
        });

        stopButton.setText("Stop");
        stopButton.setEnabled(false);
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(runButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stopButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(335, 335, 335))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(runButton)
                    .addComponent(stopButton))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setAutoscrolls(true);

        textPane.setAutoscrolls(true);
        textPane.setPreferredSize(new java.awt.Dimension(450, 400));

        javax.swing.GroupLayout textPaneLayout = new javax.swing.GroupLayout(textPane);
        textPane.setLayout(textPaneLayout);
        textPaneLayout.setHorizontalGroup(
            textPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );
        textPaneLayout.setVerticalGroup(
            textPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(textPane);

        resultTab.addTab("TextOutput", jScrollPane1);

        jScrollPane2.setViewportBorder(javax.swing.BorderFactory.createEtchedBorder());

        graphicPane.setAutoscrolls(true);
        graphicPane.setPreferredSize(new java.awt.Dimension(450, 400));

        javax.swing.GroupLayout graphicPaneLayout = new javax.swing.GroupLayout(graphicPane);
        graphicPane.setLayout(graphicPaneLayout);
        graphicPaneLayout.setHorizontalGroup(
            graphicPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );
        graphicPaneLayout.setVerticalGroup(
            graphicPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(graphicPane);

        resultTab.addTab("GraphicalOutput", jScrollPane2);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, 0, 162, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 30, Short.MAX_VALUE)
                .addComponent(resultTab, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resultTab, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        mainTab.addTab("SimpleTask", jPanel7);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        experimentProgress.setValue(0);
        experimentProgress.setStringPainted(true);

        jLabel7.setText("Progress");

        stopTaskButton.setText("Stop task");
        stopTaskButton.setEnabled(false);
        stopTaskButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopTaskButtonActionPerformed(evt);
            }
        });

        stopExperimentButton.setText("Stop experiment");
        stopExperimentButton.setEnabled(false);
        stopExperimentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopExperimentButtonActionPerformed(evt);
            }
        });

        runExperimentButton.setText("Run experiment");
        runExperimentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runExperimentButtonActionPerformed(evt);
            }
        });

        cyclesLabel.setText("Total cycles: 10");

        taskProgressLabel.setText("No task running");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cyclesLabel)
                        .addGap(18, 18, 18)
                        .addComponent(runExperimentButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(experimentProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(taskProgressLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(stopTaskButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(stopExperimentButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cyclesLabel)
                    .addComponent(runExperimentButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stopTaskButton)
                    .addComponent(taskProgressLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(experimentProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stopExperimentButton))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Data parameters");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, -1, 20));

        jLabel11.setText("Objects");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 81, 20));

        jLabel12.setText("MaxSize");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 81, 20));

        jLabel13.setText("Containers");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 81, 20));

        jLabel14.setText("Capacity");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 81, 20));

        jLabel15.setText("Free capacity");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 81, 20));

        gObjects.setText("10");
        jPanel5.add(gObjects, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 81, -1));

        gMaxSize.setText("50");
        jPanel5.add(gMaxSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 81, -1));

        gFreeCapacity.setText("any");
        gFreeCapacity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gFreeCapacityActionPerformed(evt);
            }
        });
        jPanel5.add(gFreeCapacity, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 81, -1));

        gContainers.setText("5");
        jPanel5.add(gContainers, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 81, -1));

        gCapacity.setText("100");
        gCapacity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gCapacityActionPerformed(evt);
            }
        });
        jPanel5.add(gCapacity, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 81, -1));

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setText("Algorithms");

        jCheckBox1.setSelected(true);
        jCheckBox1.setText(bp.getAlgName(0));
        checkBoxGroup.add(jCheckBox1);
        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox1ItemStateChanged(evt);
            }
        });

        jCheckBox2.setSelected(true);
        jCheckBox2.setText(bp.getAlgName(1));
        checkBoxGroup.add(jCheckBox2);

        jLabel16.setText("Cycles per setting");

        gCycles.setText("10");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jCheckBox1))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jCheckBox2))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gCycles, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox2)
                .addGap(27, 27, 27)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(gCycles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        resultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Algorithm", "Avg steps", "Min steps", "Max steps"
            }
        ));
        jScrollPane3.setViewportView(resultTable);
        resultTable.getColumnModel().getColumn(0).setHeaderValue("Algorithm");
        resultTable.getColumnModel().getColumn(1).setHeaderValue("Avg steps");
        resultTable.getColumnModel().getColumn(2).setHeaderValue("Min steps");
        resultTable.getColumnModel().getColumn(3).setHeaderValue("Max steps");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane3, 0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(120, 120, 120))
        );

        mainTab.addTab("GroupTask", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainTab, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainTab, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*
    private void objNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_objNumActionPerformed
        
    }//GEN-LAST:event_objNumActionPerformed

    private void maxSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxSizeActionPerformed
        bp.setMaxSize(Integer.parseInt(maxSize.getText()));
    }//GEN-LAST:event_maxSizeActionPerformed

    private void contNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contNumActionPerformed
        bp.setBinsNumber(Integer.parseInt(contNum.getText()));
    }//GEN-LAST:event_contNumActionPerformed

    private void capacityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capacityActionPerformed
        bp.setCapacity(Integer.parseInt(capacity.getText()));
    }//GEN-LAST:event_capacityActionPerformed
*/
    //neni potreba
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        bp.setAlg(bp.chooseAlg(jComboBox1.getSelectedIndex()));
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void runButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runButtonActionPerformed
        runButton.setEnabled(false);
        generateButton.setEnabled(false);
        stopButton.setEnabled(true);
        bp.getDp().algorithmIndex = jComboBox1.getSelectedIndex();
        bp.startRun();
    }//GEN-LAST:event_runButtonActionPerformed

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed
        bp.stop();
    }//GEN-LAST:event_stopButtonActionPerformed
/**/
    private void generateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateButtonActionPerformed
        runButton.setEnabled(true);
        DataParameters dp = new DataParameters();
        dp.capacity = Integer.parseInt(capacity.getText());
        dp.containers = (Integer.parseInt(contNum.getText()));
        dp.maxSize = (Integer.parseInt(maxSize.getText()));
        dp.objects = Integer.parseInt(objNum.getText());
        bp.setDp(dp);
        textPane.setResults(new int[]{-2});
        graphicPane.setResults(new int[]{-2});
        bp.generateData(dp);
    }//GEN-LAST:event_generateButtonActionPerformed

    private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox1ItemStateChanged
    }//GEN-LAST:event_jCheckBox1ItemStateChanged

    private void gCapacityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gCapacityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gCapacityActionPerformed

    private void gFreeCapacityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gFreeCapacityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gFreeCapacityActionPerformed

    private void stopTaskButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopTaskButtonActionPerformed
         bp.stopCurrentRepeat();
    }//GEN-LAST:event_stopTaskButtonActionPerformed

    private void runExperimentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runExperimentButtonActionPerformed
        runExperimentButton.setEnabled(false);
        stopTaskButton.setEnabled(true);
        stopExperimentButton.setEnabled(true);
        DataParameters dp = new DataParameters();
        dp.objects = Integer.parseInt(gObjects.getText());
        dp.maxSize = Integer.parseInt(gMaxSize.getText());
        dp.capacity = Integer.parseInt(gCapacity.getText());
        dp.containers = Integer.parseInt(gContainers.getText());
        dp.objects = Integer.parseInt(gObjects.getText());
        dp.cycles = Integer.parseInt(gCycles.getText());
        bp.setDp(dp);
        int i = 0;
        int count = 0;
        for (javax.swing.JCheckBox chb : checkBoxGroup) {
            if (chb.isSelected()) {
                count++;
            }
            dp.algorithms[i++] = chb.isSelected();
        }
        cyclesLabel.setText("Total cycles: " + Integer.parseInt(gCycles.getText())*count);
        experimentProgress.setMaximum(Integer.parseInt(gCycles.getText())*count);
        taskProgressLabel.setText("Task 1/" + Integer.parseInt(gCycles.getText())*count);
        RepeatRun rRun = new RepeatRun(bp,dp,experimentProgress, resultTable);
        rRun.setTaskLabel(taskProgressLabel);
           
          
        //dp.freeCapacity = Integer.parseInt(gFreeCapacity.getText());
        bp.startRepeatRun(rRun);
    }//GEN-LAST:event_runExperimentButtonActionPerformed

    private void stopExperimentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopExperimentButtonActionPerformed
       stopExperimentButton.setEnabled(false);
       stopTaskButton.setEnabled(false);
       bp.stopRepeat();
       taskProgressLabel.setText(taskProgressLabel.getText().substring(0, taskProgressLabel.getText().indexOf(":")).concat(" : Not finished."));
     
    }//GEN-LAST:event_stopExperimentButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField capacity;
    private javax.swing.JTextField contNum;
    private javax.swing.JLabel cyclesLabel;
    private javax.swing.JProgressBar experimentProgress;
    private javax.swing.JTextField freeCap;
    private javax.swing.JTextField gCapacity;
    private javax.swing.JTextField gContainers;
    private javax.swing.JTextField gCycles;
    private javax.swing.JTextField gFreeCapacity;
    private javax.swing.JTextField gMaxSize;
    private javax.swing.JTextField gObjects;
    private javax.swing.JButton generateButton;
    private binpacking.ResultPanel graphicPane;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private boolean[] selectedAlgs = new boolean[10];
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private ArrayList<javax.swing.JCheckBox> checkBoxGroup = new ArrayList<javax.swing.JCheckBox>();
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane mainTab;
    private javax.swing.JTextField maxSize;
    private javax.swing.JTextField objNum;
    private javax.swing.JTabbedPane resultTab;
    private javax.swing.JTable resultTable;
    private javax.swing.JButton runButton;
    private javax.swing.JButton runExperimentButton;
    private javax.swing.JButton stopButton;
    private javax.swing.JButton stopExperimentButton;
    private javax.swing.JButton stopTaskButton;
    private javax.swing.JLabel taskProgressLabel;
    private binpacking.ResultPanel textPane;
    // End of variables declaration//GEN-END:variables
}
